name: post-submit

on:
  push:
    branches: [master]

jobs:
  build-alpine-s390x:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          file: other/docker/alpine-s390x/Dockerfile
