---
bazel-opt_task:
  container:
    image: toxchat/toktok-stack:latest-release
    cpu: 2
    memory: 2G
  configure_script:
    - git submodule update --init --recursive
    - /src/workspace/tools/inject-repo c-toxcore
  test_all_script:
    - cd /src/workspace && bazel test -k
        --config=ci
        --build_tag_filters=-haskell
        --test_tag_filters=-haskell
        --
        //c-toxcore/...
        -//c-toxcore/auto_tests:tcp_relay_test # TODO(robinlinden): Why does this pass locally but not in Cirrus?

bazel-dbg_task:
  container:
    image: toxchat/toktok-stack:latest-debug
    cpu: 2
    memory: 2G
  configure_script:
    - git submodule update --init --recursive
    - /src/workspace/tools/inject-repo c-toxcore
  test_all_script:
    - cd /src/workspace && bazel test -k
        --config=ci
        --build_tag_filters=-haskell
        --test_tag_filters=-haskell
        --
        //c-toxcore/...
        -//c-toxcore/auto_tests:tcp_relay_test # TODO(robinlinden): Why does this pass locally but not in Cirrus?

cimple_task:
  container:
    image: toxchat/toktok-stack:latest-release
    cpu: 2
    memory: 4G
  configure_script:
    - git submodule update --init --recursive
    - /src/workspace/tools/inject-repo c-toxcore
  test_all_script:
    - cd /src/workspace && bazel test -k
        --config=ci
        --build_tag_filters=haskell
        --test_tag_filters=haskell
        --
        //c-toxcore/...
