---
bazel-opt_task:
  container:
    image: toxchat/toktok-stack:latest-release
    cpu: 2
    memory: 2G
  configure_script:
    - git submodule update --init --recursive
    - /src/workspace/tools/inject-repo c-toxcore
    - sed -i -e 's/build --config=remote/#&/' /src/workspace/.bazelrc.local
  test_all_script:
    - cd /src/workspace && bazel test -k
        --build_tag_filters=-haskell
        --test_tag_filters=-haskell
        --
        //c-toxcore/...
        -//c-toxcore/auto_tests:tcp_relay_test # Cirrus doesn't allow external network connections.

bazel-dbg_task:
  container:
    image: toxchat/toktok-stack:latest-debug
    cpu: 2
    memory: 2G
  configure_script:
    - git submodule update --init --recursive
    - /src/workspace/tools/inject-repo c-toxcore
  test_all_script:
    - cd /src/workspace && bazel test -k
        --build_tag_filters=-haskell
        --test_tag_filters=-haskell
        --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
        --
        //c-toxcore/...
        -//c-toxcore/auto_tests:tcp_relay_test # Cirrus doesn't allow external network connections.

cimple_task:
  container:
    image: toxchat/toktok-stack:latest-release
    cpu: 2
    memory: 4G
  configure_script:
    - git submodule update --init --recursive
    - /src/workspace/tools/inject-repo c-toxcore
    - sed -i -e 's/build --config=remote/#&/' /src/workspace/.bazelrc.local
  test_all_script:
    - cd /src/workspace && bazel test -k
        --build_tag_filters=haskell
        --test_tag_filters=haskell
        --
        //c-toxcore/...

freebsd_task:
  freebsd_instance:
    image_family: freebsd-14-0
  configure_script:
    - PAGER=cat ASSUME_ALWAYS_YES=YES pkg install
        cmake
        git
        gmake
        googletest
        libconfig
        libsodium
        libvpx
        opus
        pkgconf
    - git submodule update --init --recursive
  test_all_script:
    - |
      # TODO(iphydf): Investigate FreeBSD failures on these tests.
      sed -Ei -e '/\(dht_getnodes_api\)/s/^/#/' auto_tests/CMakeLists.txt
      cmake . \
        -DMIN_LOGGER_LEVEL=TRACE \
        -DMUST_BUILD_TOXAV=ON \
        -DNON_HERMETIC_TESTS=OFF \
        -DTEST_TIMEOUT_SECONDS=50 \
        -DUSE_IPV6=OFF \
        -DAUTOTEST=ON
      cmake --build . --target install
      ctest -j50 --output-on-failure --rerun-failed --repeat until-pass:6
