---
exclude:
  # shfmt doesn't support this file.
  - "other/analysis/run-clang-tidy"
  # Generated file.
  - "CHANGELOG.md"

restylers:
  - astyle:
      image: restyled/restyler-astyle:d7967bcb8b622a98524b7df1da1b02652114cf9a
      arguments: ["--options=other/astyle/astylerc"]
      include:
        - "**/*.c"
        - "**/*.h"
  - autopep8
  - black
  - clang-format:
      image: restyled/restyler-clang-format:v16.0.6
      include:
        - "**/*.cc"
        - "**/*.hh"
  - prettier-markdown
  - prettier-yaml
  - reorder-python-imports
  - shellharden
  - shfmt
  - yapf
