---
exclude:
  - "**/*.api.h"
    # shfmt doesn't support this file
  - "other/analysis/run-clang-tidy"

restylers:
  - astyle:
      arguments: ["--options=other/astyle/astylerc"]
      include:
        - "!**/*.cc"
  - autopep8
  - black
  - clang-format:
      image: restyled/restyler-clang-format:13.0.1
      include:
        - "**/*.cc"
  - prettier-yaml
  - reorder-python-imports
  - shellharden
  - shfmt
  - yapf
